version: "3.8"
services:
  homeassistant:
    container_name: homeassistant
    image: "lscr.io/linuxserver/homeassistant:2024.11.2"
    volumes:
      - /opt/homeassistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host



